on: [push, pull_request]

# Fail CI if there are warnings.
env:
  RUSTFLAGS: "-D warnings"

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@master
      with:
        components: clippy
    - run: cargo build
    - run: cargo clippy
    - run: cargo test
